version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: IlluviumTest
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  migrate:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=IlluviumTest;User=user;Password=password;SslMode=None
    networks:
      - app-network
    entrypoint: ["dotnet", "ef", "database", "update"]
    # This service runs migrations and exits

  app:
    build:
      context: .
    depends_on:
      - migrate  # Ensures migrations run before app starts
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=IlluviumTest;User=user;Password=password;SslMode=None
    networks:
      - app-network
    entrypoint: ["dotnet", "YourApp.dll"]

volumes:
  db_data:

networks:
  app-network:
